import "../globals.css";
import type { Metadata } from "next";
import Navbar from "@/components/layouts/navbar";

export const metadata: Metadata = {
  title: "Expense",
  description: "Generated by create next app",
};

export default function GeneralLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <div className="min-h-screen">
      <header className="sticky top-0 z-40 border-b bg-backgroun">
        <div className="container flex h-16 items-center justify-between py-4">
          <Navbar />
        </div>
      </header>
      <main>{children}</main>
    </div>
  );
}
