import "../../globals.css";
import type { Metadata } from "next";
import React from "react";
import Sidebar from "@/app/(user)/dashboard/_components/sidebar";

export const metadata: Metadata = {
  title: "Expense",
  description: "Generated by create next app",
};

export default function GeneralLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <div className="min-h-screen">
      <div className={"flex"}>
        <Sidebar />
        <div>{children}</div>
      </div>
    </div>
  );
}
